# Generated by Django 2.1.7 on 2019-02-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreCurso', models.CharField(max_length=100)),
                ('Modulos', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
