# Generated by Django 2.1.7 on 2019-02-26 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Foro', '0002_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nota', models.PositiveSmallIntegerField(default=0)),
                ('Estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Foro.Estudiante')),
                ('NombreCurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Foro.Curso')),
            ],
        ),
    ]
